#string
nome = "João Paulo"
print(nome)
print(type(nome))
print(nome.lower())
print(nome.upper())
print(len(nome))
print(nome[0])
print(nome[9])
print(nome[4])
print(nome[0:4])
print(nome[4:])
print(nome[:4])
print(nome.startswith("J"))
print(nome.startswith("j"))
print("J" in nome)
print(nome.endswith("o"))
termina_com_o = nome.endswith("o")
print("------")
print(termina_com_o)
print(nome.count("o"))

print('-----')
nome = "João PaulO"
#nome = nome.lower()
print(nome)
print(nome.count("o") + nome.count("O"))
print(nome.capitalize())
print(nome.title())